# The URL the site will be built for
base_url = "https://tallentire.dev"
theme = "dose"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

external_links_target_blank = true

taxonomies = [
    { name = "tags", feed = true },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

social_media = [
    { name = "GitHub", url = "https://github.com/danieltallentire" },
    { name = "LinkedIn", url = "https://www.linkedin.com/in/danieltallentire/" },
]
default_theme = "dark" # or "light"